export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const START_BUILDING = 'START_BUILDING';

export const SWITCH_SHOWED_TIP_STATE = 'SWITCH_SHOWED_TIP_STATE';

export const INIT_MONTH_INGREDIENTS = 'INIT_MONTH_INGREDIENTS';
export const CALC_TOTAL_PRICE = 'CALC_TOTAL_PRICE';

export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const INIT_CONTROLS = 'INIT_CONTROLS';
export const SET_CONTROLS = 'SET_CONTROLS';

export const PURCHASE_BASKET = 'PURCHASE_BASKET';
export const PURCHASE_BASKET_START = 'PURCHASE_BASKET_START';
export const PURCHASE_BASKET_SUCCESS = 'PURCHASE_BASKET_SUCCESS';
export const PURCHASE_BASKET_FAIL = 'PURCHASE_BASKET_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const REMOVE_BADGE= 'REMOVE_BADGE';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

export const FETCH_MANAGER_DATA = 'FETCH_MANAGER_DATA';
export const SET_MANAGER_DATA = 'SET_MANAGER_DATA';
export const UPDATE_PRICE = 'UPDATE_PRICE';